// Stock Database
export const STOCK_DATABASE = {
  TW: [
    { code: "2330", name: "台積電", nameEn: "TSMC" },
    { code: "2317", name: "鴻海", nameEn: "Hon Hai" },
    { code: "2454", name: "聯發科", nameEn: "MediaTek" },
    { code: "2412", name: "中華電", nameEn: "Chunghwa Telecom" },
    { code: "2882", name: "國泰金", nameEn: "Cathay FHC" },
    { code: "2881", name: "富邦金", nameEn: "Fubon FHC" },
    { code: "2886", name: "兆豐金", nameEn: "Mega FHC" },
    { code: "2891", name: "中信金", nameEn: "CTBC FHC" },
    { code: "2303", name: "聯電", nameEn: "UMC" },
    { code: "2308", name: "台達電", nameEn: "Delta Electronics" },
    { code: "2357", name: "華碩", nameEn: "ASUS" },
    { code: "2382", name: "廣達", nameEn: "Quanta" },
    { code: "2395", name: "研華", nameEn: "Advantech" },
    { code: "3008", name: "大立光", nameEn: "Largan" },
    { code: "3711", name: "日月光投控", nameEn: "ASE Technology" },
    { code: "5880", name: "合庫金", nameEn: "Taiwan Business Bank" },
    { code: "6505", name: "台塑化", nameEn: "Formosa Petrochemical" },
    { code: "1301", name: "台塑", nameEn: "Formosa Plastics" },
    { code: "1303", name: "南亞", nameEn: "Nan Ya Plastics" },
    { code: "0050", name: "元大台灣50", nameEn: "Yuanta Taiwan 50 ETF" },
    { code: "0056", name: "元大高股息", nameEn: "Yuanta High Dividend ETF" },
  ],
  US: [
    { code: "AAPL", name: "Apple", nameCn: "蘋果" },
    { code: "MSFT", name: "Microsoft", nameCn: "微軟" },
    { code: "GOOGL", name: "Alphabet (Google)", nameCn: "谷歌" },
    { code: "AMZN", name: "Amazon", nameCn: "亞馬遜" },
    { code: "TSLA", name: "Tesla", nameCn: "特斯拉" },
    { code: "META", name: "Meta (Facebook)", nameCn: "Meta" },
    { code: "NVDA", name: "NVIDIA", nameCn: "輝達" },
    { code: "TSM", name: "Taiwan Semiconductor (ADR)", nameCn: "台積電ADR" },
    { code: "JPM", name: "JPMorgan Chase", nameCn: "摩根大通" },
    { code: "V", name: "Visa", nameCn: "Visa" },
    { code: "WMT", name: "Walmart", nameCn: "沃爾瑪" },
    { code: "JNJ", name: "Johnson & Johnson", nameCn: "嬌生" },
    { code: "PG", name: "Procter & Gamble", nameCn: "寶僑" },
    { code: "DIS", name: "Walt Disney", nameCn: "迪士尼" },
    { code: "NFLX", name: "Netflix", nameCn: "網飛" },
    { code: "PYPL", name: "PayPal", nameCn: "PayPal" },
    { code: "INTC", name: "Intel", nameCn: "英特爾" },
    { code: "AMD", name: "AMD", nameCn: "超微" },
    { code: "BABA", name: "Alibaba", nameCn: "阿里巴巴" },
    { code: "NKE", name: "Nike", nameCn: "耐克" },
    { code: "BA", name: "Boeing", nameCn: "波音" },
    { code: "COST", name: "Costco", nameCn: "好市多" },
    { code: "MA", name: "Mastercard", nameCn: "萬事達卡" },
  ],
};

export const STORAGE_KEYS = {
  WATCHLIST: "ai_investment_watchlist",
  HISTORY: "ai_investment_history",
  API_KEY: "ai_investment_api_key",
  MODEL: "ai_investment_model",
  STOCK_DB_TW: "ai_investment_stock_db_tw",
  STOCK_DB_US: "ai_investment_stock_db_us",
  STOCK_DB_TIMESTAMP: "ai_investment_stock_db_timestamp",
};
